import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Photobooth",
  description: "Generated by create next app",

  openGraph: {
    title: "My Photobooth App",
    description: "Create fun memories instantly",
    url: "https://photobooth-m.vercel.app",
    siteName: "Photobooth",
    images: [
      {
        url: "/assets/Twitter.png",
        width: 1200,
        height: 630,
        alt: "Photobooth Preview",
      },
    ],
    type: "website",
  },

  twitter: {
    card: "summary_large_image",
    title: "My Photobooth App",
    description: "Create fun memories instantly",
    images: ["/assets/Twitter.png"],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/assets/logo.png" />
      </head>
      <body
        className={`${inter.className}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
